[package]
name = "dynamic_midi"
version = "0.1.0"
edition = "2021"

[lib]
name = "dynamic_midi"
path = "lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
winapi = "0.3.9"
widestring = "1.0.2"
